site_name: AWS Organization Construct Library
repo_url: https://github.com/JumpToTheCloud/aws-organizations

nav:
  - Homepage:
      - index.md
      - Organization: organization.md
      - Organizational Units: organization-unit.md
      - Accounts: account.md
      - Policies: policy.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
  custom_dir: docs/overrides

extra:
  version:
    provider: mike
    default: latest

plugins:
  - mike:
      version_selector: true

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - tables
  - toc:
      permalink: true
      toc_depth: 4
